### ISSUE TITLE
Tray icon?

### ISSUE THREAD

**Issue by somasis** [jgke/connman-gtk#1]
This would make it much more usable outside of GNOME.

**Comment by jgke** [comment]
The main problem with status icons is that the support in GTK is now [deprecated](https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html) for whatever reason (probably that Gnome doesn't support them anymore). If they are sensible about it, they won't remove the support but you never know. I'm not against the idea, however, so patches are welcome about it.

**Comment by Somasis** [comment]
Good start :+1:

**Comment by jgke** [comment]
Slowly but steadily.

**Comment by jgke** [comment]
What features would actually be needed? I implemented the base for it, and now it has buttons for opening the main window and closing the program. Probably a list of technologies with services as submenus for quick connecting? Features like enabling or disabling technologies isn't used as often so it should be fine to put them only to the client.

**Comment by Somasis** [comment]
It might be good to have it be something like NetworkManager's tray icon. Scanned connections, active one in bold, then on right click maybe it could have the technology enabling and disabling, etc.

**Comment by hasufell** [comment]
guys, are you aware of https://github.com/tbursztyka/connman-ui?

I'm not sure if it would make any sense to join effort there or make both things compatible, but it looks like duplication of effort.

**Comment by Somasis** [comment]
I had originally been using that, but it seems a lot more limited in terms of desktop integration in the way that this one tries for. In addition, it seems to lack a lot of configuration options and just isn't very nice to use compared to this implementation.

**Comment by jgke** [comment]
What kind of configuration would you actually like to see? Also, with the tray specification being what it is you can't really get any more desktop integration than what tbursztyka's implementation gives without actually doing platform-specific things.

**Comment by Somasis** [comment]
The configuration implemented already seems to be good enough, to me.

In terms of desktop integration, I mean more like adhering to the interface guidelines that most programs follow; connman-ui seems to use custom icons, weird ways of opening configuration menus, and so on, and I suppose I just dislike the tray icon, compared to NetworkManager's own applet, which is much better designed, imo

**Comment by jgke** [comment]
Just pushed out commits that include additional functionality - listing technologies and services within, and allowing connecting / disconnecting them by clicking them. It still has some work left regarding some corner cases but I don't really thing any other functionality should be there (perhaps tethering?) as they would clutter the menu.

**Comment by Somasis** [comment]
I think it might be better if common connection sources (wired/wireless/bluetooth) have their available technologies in the menu, without being in another menu level. Otherwise looks nice.

**Comment by jgke** [comment]
Do you perhaps mean services rather than technologies? I think it would, especially in the case of wireless, cause way too many entries in the list. Having the connected-state of the technology visible might be useful though.

**Comment by Somasis** [comment]
Services, right. Maybe do like nm-applet does? When the list of available services goes over about 8 or so, it overflows the extraneous into a separate menu.

**Comment by jgke** [comment]
Maybe something like having more than one service would mean a submenu, but only one service means directly showing it? Another option would be showing services that have been previously connected to. The most problematic use case would then be that one doesn't have any wireless services visible and then the user gets confused since no wireless technology would be visible (or perhaps, grayed out).

**Comment by jgke** [comment]
I implemented features for starting straight to the tray and changing the icon based on the best available connection. I don't think I'll be complicating the current menu design, I like the current one. Are there any simple features before I close this feature request?

**Comment by somasis** [comment]
Nope, seems good to me. Thanks a lot :+1:

**Comment by matsaman** [comment]
Even with `--tray` the main window is briefly shown before being disappeared. This is confusing/tedious and reminds one of trying to do anything at all via a command on Windows.

Clicking on the icon once opens the main window, but clicking it again does not hide it, which is inconsistent.

Between Windows, macOS, and nm-applet, I think they all have a connection list just from left-clicking the icon, and not requiring you to either open up a large window, or right click and navigate about. It's your software, and I can do the work to get what I want if I want it enough, but that is what I for one would prefer, and what I expect most would.
