### ISSUE TITLE
No tray icon with stalone tray

### ISSUE THREAD

**Issue by Astaoth** [jgke/connman-gtk#15]
Hi,

Even build with the "--enable-status-icon=yes" option, there is no tray icon displayed with Stalonetray.

**Comment by jgke** [comment]
I have some breakage as well regarding the icon, I'm suspecting GTK... What GTK version do you have?

**Comment by Astaoth** [comment]
I have gtk3 3.18.5 and gtk2 2.24.28 installed.

**Comment by jgke** [comment]
Cannot reproduce, the icon shows up just fine over here. Does connman-gtk show any warnings or errors in stderr?

**Comment by Astaoth** [comment]
No there is nothing written.

**Comment by jgke** [comment]
Oh, and do check the settings menu, there's a enable/disable status icon checkbox (requires restarting connman-gtk to take effect).

**Comment by Astaoth** [comment]
Right, I didn't see it. However, the first time I enabled the "Launch to tray by default" option. So now, when I launch it, it starts minimized but I don't have the status icon :/.

**Comment by jgke** [comment]
Hm, so at least a option like --no-tray is missing... Run the command 'gsettings set net.connman.gtk launch-to-tray false'.

**Comment by Astaoth** [comment]
Thank you.
I think "Launch to tray by default" option should also enable the "Use status icon". It will avoid this kind of problem.

**Comment by jgke** [comment]
Or alternatively do nothing if the status icon is not selected. Quality code, who the hell wrote this... Culprit is main.c:628, I'll push out the fix on Thursday.

**Comment by Astaoth** [comment]
Thank you :)
