### ISSUE TITLE
WPA2 Enterprise support

### ISSUE THREAD

**Issue by onny** [jgke/connman-gtk#25]
Hey,
it would be very usefull to support WPA2 Enterprise authentication method. Like a dialog asking for username and password.
Otherwise, connections to eduroam or university networks have to be configured manually :(

Best regards, Jonas

**Comment by jgke** [comment]
This is unfortunately a limitation at ConnMan's end, see #5. WPA2 Enterprise networks require a service file at /var/lib/connman before they can be connected to, but ConnMan doesn't provide any API for writing there, or specifying connection parameters manually. VPN side has some function for it, but I haven't tested whether it works.

**Comment by cyruseuros** [comment]
Would it be possible to do what `cmst` does and write to `/var/lib/connman/<file>.config`? They use textual templates, but I don't see why a GUI to create those templates would not work.
