### ISSUE TITLE
Settings schema 'net.connman.gtk' is not installed

### ISSUE THREAD

**Issue by rgoggans** [jgke/connman-gtk#30]
Got this error upon running connman-gtk after building and installing with no issues on Alpine Linux. Any help is appreciated.

```
(connman-gtk:24907): GLib-GIO-CRITICAL **: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(connman-gtk:24907): GLib-GIO-ERROR **: Settings schema 'net.connman.gtk' is not installed

[1]    24907 trace trap  connman-gtk
exit 133
```

**Comment by jgke** [comment]
You need to install the gschema file to your system (for handling settings), this should be handled by "ninja install"... except that it isn't. I'll fix that in a moment. You can workaround this by running
    `glib-compile-schemas /usr/local/share/glib-2.0/schemas`
(or whereever it installed it for you)

**Comment by jgke** [comment]
...or, you can just pull the latest head, it should fix the problem :)
